
spring:
    application:
        name: crm-manage
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    http:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
    redis:
      host: localhost
      port: 6379
    profiles:
        active: @profileActive@
#    邮件服务
    mail:
      default-encoding: UTF-8
      host: smtp.163.com
      username: spring_boot@163.com
      password: abc123455
#      port: 25
      test-connection: false
      properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
                  required: true
#                connectiontimeout: 5000
#                timeout: 3000
#                writetimeout: 5000

server:
    port: 8080
    tomcat:
        accesslog:
          debug: true #请求响应数据调试
    context-path: /manage
#这里提醒注意点,如果想要拦截404错误的话,需要在spring boot中做如下设置
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false
swagger:
    basepackage: com.yy.crm
    service:
        name: crm-manage
        description: crm-manage 后端服务
        developer: luyuanx2
security:
    basic:
        enabled: false
yy:
  manage:
    url: http://192.168.1.55:8999/login
  security:
    social:
      tablePrefix: yy_
      qq:
        app-id: 1106432571
        app-secret: xL2DDQ1RLkvUfbpc
        provoderId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        provoderId: weixin
      filterProcessesUrl: /qqLogin
    oauth2:
      #storeType: redis
      clients[0]:
        clientId: lyy
        clientSecret: lyysecret
        accessTokenValiditySeconds: 7200
      clients[1]:
        clientId: lyy1
        clientSecret: lyysecret1
        accessTokenValiditySeconds: 7200
      jwtSigningKey: lyy
#flyway.locations=db/migration/{vendor}

