spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: root
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
# 配置日志打印信息
#logging.level.root=INFO
#logging.level.com.itmuch=DEBUG
